[FR] Optionally pass nested schema for further validation
endgameinc/eql pull request #68
Opened 2023-06-24 11:34 UTC by Mikaayenson

## Issues
N/A

## Details
*Describe details about your requested changes*

We want to validate functions that use nested fields. This WIP enables us to pass down the schema for os-specific nested fields and validate nested fields belong to a parent field (and that the nested fields existed per stack).

2023-06-26 18:51 UTC, Mikaayenson commented
> Looks like it's `ubuntu-latest` that's getting in the way of your Python 2.7 validation

Yup. May have to let it go based on the [deprecation](https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/).

2023-07-11 20:53 UTC, Mikaayenson commented on .github/workflows/pythonpackage.yml
> +    runs-on: ubuntu-20.04
```suggestion
    runs-on: ubuntu-22.04
```

2023-07-12 16:23 UTC, eric-forte-elastic approved these changes

2023-07-12 16:39 UTC, terrancedejesus approved these changes

2023-07-12 16:41 UTC, brokensound77 commented on CHANGELOG.md
> +* Support for schema validation on nested fields
```suggestion
* Support for exposing nested fields for validation
```

2023-07-13 06:42 UTC, brokensound77 commented on eql/signatures.py
> +    def validate(cls, arguments, event_type=None, schema=None):  # type: (list[NodeInfo]) -> int
update type hinting

```suggestion
    def validate(cls, arguments, event_type=None, schema=None):  # type: (list[NodeInfo, str, dict]) -> int
```

2023-07-13 06:55 UTC, brokensound77 requested changes
hold off merging until further discussions

2023-07-27 00:25 UTC, closed without merging

2023-07-27 00:26 UTC, Mikaayenson commented
Hijacking https://github.com/endgameinc/eql/pull/71